export default function Terms() {
  return (
    <div className="page">
      <div className="container legal-page">
        <div className="eyebrow">Legal</div>
        <h1 style={{ fontSize: '2rem', marginTop: '0.5rem', marginBottom: '1.5rem' }}>Terms &amp; Conditions</h1>

        <div className="panel reading-card">
          <h4>User Responsibilities</h4>
          <p>
            You agree to provide birth information accurately to the best of your knowledge and
            to use AstroYantra for personal, lawful, non-commercial purposes unless otherwise
            agreed with us in writing.
          </p>
        </div>

        <div className="panel reading-card">
          <h4>Acceptable Use</h4>
          <p>
            You agree not to misuse the service, including attempting to disrupt or overload our
            servers, scraping the site at scale, or using it to generate content intended to
            harass, defame, or mislead others.
          </p>
        </div>

        <div className="panel reading-card">
          <h4>Intellectual Property</h4>
          <p>
            The AstroYantra name, logo, design, and underlying software are the property of
            AstroYantra and its creators. Your individual chart readings are generated for your
            personal use; you're welcome to save or share your own results.
          </p>
        </div>

        <div className="panel reading-card">
          <h4>Limitation of Liability</h4>
          <p>
            AstroYantra is provided "as is" without warranties of any kind. To the fullest extent
            permitted by law, AstroYantra and its team are not liable for any decisions made, or
            outcomes experienced, based on readings generated by this platform.
          </p>
        </div>

        <div className="panel reading-card">
          <h4>No Guarantee of Prediction Accuracy</h4>
          <p>
            Astrology is not a scientifically validated predictive system. AstroYantra makes no
            guarantee that any reading, forecast, or compatibility score reflects future events
            or outcomes with any degree of accuracy.
          </p>
        </div>

        <p className="muted" style={{ fontSize: '0.82rem', marginTop: '1rem' }}>
          Last updated: 2026. By using AstroYantra, you agree to these terms.
        </p>
      </div>
    </div>
  );
}
